### PR TITLE
[WED] v0.2.2_rdo to v0.2.4_rdo (RP-246) (RP-243)

### PR DESCRIPTION
**Pull request by JeanChristopheMorinRodeoFX**

### CODE REVIEW

**Comment by kookiCT** [comment]
Why are there still some of Julien's commits in this PR ?

**Comment by JeanChristopheMorinRodeoFX** [comment]
@kookiCT I don't know, will try to find what I did wrong and fix that.

**Comment by JeanChristopheMorinRodeoFX** [comment]
Because they are not in `master_rdo` branch but in `master` instead. So when I merge `master` into `dev_update_app` which is branched off `master_rdo`, these commits appear.

Do we want those commits to be in `master_rdo`?

**Comment by kookiCT** [comment]
"master" branch cleaned up (extracted "dev_xsi_render_settings" branch and "v0.1.7_rdo" tag for historical purposes)

**Comment by kookiCT** [comment]
:+1:

**Comment by darkvertex** [comment]
:+1:

**Pull request merged**
