### PR TITLE
[WED] Add support for tk-katana engine

### PR DESCRIPTION
**Pull request by kookiCT**
This change is [Reviewable](https://reviewable.io/reviews/rodeofx/tk-multi-setframerange/4)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/rodeofx/tk-multi-setframerange/pull/4" target="_blank">ReviewNinja

**Comment by darkvertex** [comment]
LGTM :+1:

**Comment by awierzchowski** [comment]
:+1:

**Comment by frenchdog** [comment]
:+1:

**Pull request merged**
